project_name: compozify

release:
  prerelease: auto
  draft: true
  name_template: "Compozify {{.Version}}"

before:
  hooks:
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make completions
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make manpages COMPOZIFY_VERSION={{.Version}}

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: bin/compozify
    main: ./cmd/compozify
    ldflags:
      - -s -w -X github.com/profclems/compozify/internal/version.Version={{.Version}} -X github.com/profclems/compozify/internal/version.BuildDate={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/compozify
    main: ./cmd/compozify
    ldflags:
      - -s -w -X github.com/profclems/compozify/internal/version.Version={{.Version}} -X github.com/profclems/compozify/internal/version.BuildDate={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    binary: bin/compozify
    main: ./cmd/compozify
    ldflags:
      - -s -w -X github.com/profclems/compozify/internal/version.Version={{.Version}} -X github.com/profclems/compozify/internal/version.BuildDate={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "compozify_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/compozify*.1
  - id: macos-archive
    builds: [macos]
    name_template: "compozify_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - ./share/man/man1/compozify*.1
  - id: windows-archive
    builds: [windows]
    name_template: "compozify_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

nfpms: #build:linux
  - license: MIT
    maintainer: Clement Sam
    homepage: https://github.com/profclems/compozify
    bindir: /usr
    dependencies:
      - git
    description: Compozify is a tool mainly for converting docker run commands to docker-compose files
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/compozify*.1"
        dst: "/usr/share/man/man1"
      - src: "./share/bash-completion/completions/compozify"
        dst: "/usr/share/bash-completion/completions/compozify"
      - src: "./share/fish/vendor_completions.d/compozify.fish"
        dst: "/usr/share/fish/vendor_completions.d/compozify.fish"
      - src: "./share/zsh/site-functions/_compozify"
        dst: "/usr/share/zsh/site-functions/_compozify"